#
# Elasticsearch Dockerfile with HQ plugin
#
# https://github.com/dockerfile/elasticsearch

# Pull base image
FROM elasticsearch:latest

MAINTAINER Konrad Oleksiuk <konole@gmail.com>

# Install plugin
RUN bin/plugin install royrusso/elasticsearch-HQ
